# Docker Compose for production deployment
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        - VITE_NAVER_MAP_CLIENT_ID=${VITE_NAVER_MAP_CLIENT_ID}
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: open-spot-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NGINX_WORKER_PROCESSES=auto
    restart: unless-stopped
    networks:
      - openspot-network
    volumes:
      # Persistent logs
      - nginx_logs:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.openspot.service=frontend"
      - "com.openspot.environment=production"

networks:
  openspot-network:
    external: true
    name: open_spot_openspot-network

volumes:
  nginx_logs:
    driver: local
    name: open-spot-nginx-logs
