import { defineConfig } from 'orval';

export default defineConfig({
  openspot: {
    input: {
      target: './openapi.yaml',
    },
    output: {
      mode: 'tags-split',
      target: './src/api/generated',
      schemas: './src/api/generated/model',
      client: 'axios',
      mock: false,
      clean: true,
      prettier: true,
      override: {
        mutator: {
          path: './src/api/axios-instance.ts',
          name: 'customAxiosInstance',
        },
        header: (info) => [
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          `${info.title}`,
          `OpenAPI spec version: ${info.version}`,
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: 'prettier --write',
    },
  },
});
